# This is a basic workflow to help you get started with Actions

name: variable parameter pipeline

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Training: "GitHub Actions"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    name: Greet user in 1st Job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      NAME: "Suparna"
      Training: "Python"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Greet user
        run: echo "Hello $NAME, this is $Training training.."

  hello-again:
    name: Greet user in 2nd Job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      NAME: "Shreyan"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Greet user
        run: echo "Hello $NAME, this is $Training training.."
